/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>

#include "gpio_driver.h"
#include "uart_driver.h"
#include "stm32f401xe.h"

void delay(volatile uint32_t count) {
    while(count--);
}

void blinky(void){
	GPIO_ClockEnable(GPIOA);
	GPIO_PinMode(GPIOA, 5, GPIO_MODE_OUTPUT);

	while(1){
		GPIO_TogglePin(GPIOA, 5);
		delay(500000);
	}
}

void uart_sender(void){
	printf("Entering the function\n");
	UART_ClockEnable(USART2);
	UART_GPIO_Init();
	UART_Init(USART2, 115200, 16000000);

	printf("UART function was initialized\n");

	delay(100000);


	UART_SendString(USART2, "\r\n=== UART Test Menu ===\r\n");
	UART_SendString(USART2, "1. Blink LED\r\n");
	UART_SendString(USART2, "2. Send message\r\n");
	UART_SendString(USART2, "3. Echo mode\r\n");
	UART_SendString(USART2, "Select: ");

    while(1) {
    	printf("Entering the embedded loop\n");
        uint8_t choice = UART_ReceiveChar(USART2);
        UART_SendChar(USART2, choice);
        UART_SendString(USART2, "\r\n");

        switch(choice) {
            case '1':
                UART_SendString(USART2, "LED toggling...\r\n");
                GPIO_ClockEnable(GPIOA);
                GPIO_PinMode(GPIOA, 5, GPIO_MODE_OUTPUT);
                GPIO_TogglePin(GPIOA, 5);
                break;
            case '2':
                UART_SendString(USART2, "Hello from STM32!\r\n");
                break;
            case '3':
                UART_SendString(USART2, "Echo mode - press ESC to exit\r\n");
                while(1) {
                    uint8_t c = UART_ReceiveChar(USART2);
                    if(c == 27) break;  // ESC key
                    UART_SendChar(USART2, c);
                }
                break;
        }
        UART_SendString(USART2, "\r\nSelect: ");
    }
}

int main(void)
{
//	blinky();
	uart_sender();
}
