/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#include "gpio_driver.h"
#include "stm32f401xe.h"

void delay(volatile uint32_t count) {
    while(count--);
}

//example code to test my custom made API for GPIO
void blinky(void){
	GPIO_ClockEnable(GPIOA);
	GPIO_PinMode(GPIOA, 5, GPIO_MODE_OUTPUT);

	while(1){
		GPIO_TogglePin(GPIOA, 5);
		delay(500000);
	}
}


int main(void)
{
	blinky();
}
